name: giphy_gifs_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.6.0
  json_serializable: ^6.8.0
  mockito: ^5.5.0
